# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eabb9e84737130a8dc0ba85635af2b4fa8703c186115575ce7784b421bf0604cdb7841d6ba16ff3eec57e16d209402e4f55b56a6863608daf507eace9166a33

test:
  secret_key_base: bcec983c7c41747b6dbd8f6caf1bebc4c98c499826969b1dfa06e07c206f1f327501723ccb1587a75396fd4cb2acece4e7f32f932c717ec7682df42150ba729e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
